"""create file table

Revision ID: 437daf4c295f
Revises: 
Create Date: 2021-03-16 11:04:17.699421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437daf4c295f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=150), nullable=True),
    sa.Column('filelink', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
